services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  telemetry-handle-server:
    image: softjey/telemetry-handle-server:1.0.0
    container_name: telemetry-handle-server
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  # Service only for testing
  telemetry-service:
    image: softjey/telemetry-service:1.0.0
    container_name: telemetry-service
    depends_on:
      - telemetry-handle-server
    profiles:
      - testing

volumes:
  mongo_data:
